### PR TITLE
Change prints to logging

### PR DESCRIPTION
**Pull request by PaulBrownMagic**
I needed to suppress the print statement output for use in application. So this moves all prints to logging, either at debug or info level. I also updated the tests so that the information that was previously provided by print statements is still provided by the logger.

### CODE REVIEW

**Comment by ian-andrich** [comment]
Apologies, haven't been checking github.

**Comment by PaulBrownMagic** [comment]
I know things are a bit crazy at the moment!

What do you think of moving the prints to logging? I think output should be suppressed, but we've still got easy access to it by simply setting the logging level to info for what we'd have printed now, or debug for all the detail.

**Comment by ian-andrich** [comment]
I think it's a great idea. Frankly I should have coded it that way to begin with.

**Comment by PaulBrownMagic** [comment]
Any thoughts on getting this merged?

**Comment by ian-andrich** [comment]
Wow. I meant to merge this.

**Comment by ian-andrich** [comment]
Done.

**Pull request merged**
