### PR TITLE
Multiple changes

### LINKED ISSUE #3: remove __pycache__

### PR DESCRIPTION
**Pull request by cmungall**
fixes various issues

### CODE REVIEW

**Comment by cmungall** [comment]
Apologies for the stream of issues and bundling everything into one PR, I can try and separate some of these if easier.

**Comment by ian-andrich** [comment]
And done.

**Comment by ian-andrich** [comment]
Closing was definitely not my intention, apologies, still new to the GitHub open source workflow.

**Comment by ian-andrich** [comment]
BTW, I extended collaborator privileges since you are actively using and contributing.

**Pull request merged**
